Fix retagging

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,6 +58,7 @@ jobs:
       - name: Build
         run: |
           ./scripts/build.sh --cache-from ${{ env.IMAGE }}
+          docker tag subscity ${{ env.IMAGE }} || echo "couldn't retag"
 
       - name: Cleanup pre-existing MySQL data dir
         run: |
